<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>XgFilter_Lib</RootNamespace>
    <AssemblyName>XgFilter_Lib</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ConvertXgToJson_Lib\ConvertXgToJson_Lib\ConvertXgToJson_Lib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Enums\" />
    <Folder Include="Projection\" />
    <Folder Include="Filtering\" />
  </ItemGroup>

</Project>